### ISSUE TITLE
Can't open documentation with option --open on ubuntu

### ISSUE THREAD

**Issue by vonglasow** [hoaproject/Kitab#32]
To open the generated documentation, the code loop on list of utilities, locate the first tool which exist and use it.

see https://github.com/hoaproject/Kitab/blob/master/src/Bin/Compile.php#L223-L240

On ubuntu the binary `open` ([openvt](http://manpages.ubuntu.com/manpages/precise/en/man1/openvt.1.html)) exist and `xdg-open` too . When we try to run the `open` command, we got this error `Couldn't get a file descriptor referring to the console` because we try to starts a program on another virtual terminal.

To define which command to use we need also to know on which OS we are. On ubuntu, we should keep using `xdg-open` even if the command `open` exist.

**Comment by Hywan** [comment]
Or we iterate over `xdg-open` before `open` :-p. Would it work?

**Comment by vonglasow** [comment]
Yes, it will works! Now, what about in specific case where you have `xdg-open` and `open` on your mac for example :D I know it's not a common case.

**Comment by Hywan** [comment]
Well, we will have a new bug if it happens one day.
